name: emocities
dependencies:
  - geopandas
  - matplotlib
  - numpy
  - scipy
  - pandas
  - jupyter
  - s3fs
  - pip
  - pip:
    - pyubx2
    - tilemapbase
    - dotmap
    - nepy
    - nepy
    - simplekml
